apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: front-end-certificate
  namespace: photo-album-front-end
spec:
  secretName: front-end-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - photos.home.ruchij.com
