apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: photo-album-front-end
spec:
  selector:
    app: front-end
    branch: {{ git_branch }}
  ports:
    - name: nextjs-port
      port: 3000
